server:
  port: ${PORT_MOVIE:8011}
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:movie-service-test}
    username: sa
    password:
    driverClassName: org.h2.Driver
    generate-unique-name: false
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate.format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
